# This is a basic workflow to help you get started with Actions

name: 中华新华字典数据库

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          wget https://github.com/pwxcoo/chinese-xinhua/archive/refs/heads/master.zip
          unzip master.zip
          mv chinese-xinhua-master/data ./
          mv chinese-xinhua-master/README.md ./data/
          rm -rf chinese-xinhua-master
          mv data xinhua
          ls -l xinhua
          zip -r xinhua.zip xinhua
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 中华新华字典数据库
          release_name: 中华新华字典数据库
          body: |
            Release 
            - 中华新华字典数据库
            - https://github.com/pwxcoo/chinese-xinhua
            - xinhua.zip
            - 17 Jan 2019
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: xinhua.zip
          asset_name: xinhua.zip
          asset_content_type: application/zip
